AllCops:
  DisabledByDefault: true

Bundler:
  Enabled: true
Bundler/DuplicatedGem:
  Enabled: false

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Lint:
  Enabled: true
Lint/HandleExceptions:
  AllowComments: true

Metrics:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 120

Naming:
  Enabled: true

Security:
  Enabled: true

Style:
  Enabled: true
Style/ExpandPathArguments:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false