---
language: ruby
sudo: false
dist: trusty
rvm:
  - 1.9.3
  - 2.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - rbx-3
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.7.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  fast_finish: true
before_install:
  - gem install bundler --version '~> 1.17'
jobs:
  include:
    - stage: test
      script: bundle exec rspec spec
    - &code_quality
      stage: code_quality
      script: bundle exec rubocop
      rvm: 2.3.8
    - <<: *code_quality
      rvm: 2.4.6
    - <<: *code_quality
      rvm: 2.5.5
    - <<: *code_quality
      rvm: 2.6.3
    - <<: *code_quality
      rvm: rbx-3
    - <<: *code_quality
      rvm: jruby-9.1.17.0
    - <<: *code_quality
      rvm: jruby-9.2.7.0
    - <<: *code_quality
      rvm: ruby-head
    - <<: *code_quality
      rvm: jruby-head
notifications:
  email:
    - semmons99@gmail.com
    - andreas@aloop.org
    - weppos@weppos.net
